"""创建tools表

Revision ID: eba7484a73b6
Revises: 3ec2a03ce32e
Create Date: 2026-06-18 16:35:02.712866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba7484a73b6'
down_revision: Union[str, Sequence[str], None] = '3ec2a03ce32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('name', sa.String(length=200), nullable=False, comment='工具名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='工具描述'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='工具类型: builtin/http_api/custom_function'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态: enabled/disabled/error'),
    sa.Column('config', sa.JSON(), nullable=True, comment='工具配置（因类型而异）'),
    sa.Column('function_definition', sa.JSON(), nullable=True, comment='Function Calling 定义（OpenAI 格式）'),
    sa.Column('call_count_7d', sa.Integer(), nullable=False, comment='近7天调用次数'),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='成功率 %'),
    sa.Column('avg_latency', sa.Integer(), nullable=False, comment='平均延迟 ms'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='工具表'
    )
    op.create_table_comment(
        'model_provider',
        '模型供应商表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'models',
        '大语言模型表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'permissions',
        '权限表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'prompt_versions',
        'Prompt 版本历史表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'prompts',
        'Prompt 模板表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'role_permissions',
        '角色权限关联表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'roles',
        '角色表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'user_roles',
        '用户角色关联表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'users',
        '用户表',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='用户表',
        schema=None
    )
    op.drop_table_comment(
        'user_roles',
        existing_comment='用户角色关联表',
        schema=None
    )
    op.drop_table_comment(
        'roles',
        existing_comment='角色表',
        schema=None
    )
    op.drop_table_comment(
        'role_permissions',
        existing_comment='角色权限关联表',
        schema=None
    )
    op.drop_table_comment(
        'prompts',
        existing_comment='Prompt 模板表',
        schema=None
    )
    op.drop_table_comment(
        'prompt_versions',
        existing_comment='Prompt 版本历史表',
        schema=None
    )
    op.drop_table_comment(
        'permissions',
        existing_comment='权限表',
        schema=None
    )
    op.drop_table_comment(
        'models',
        existing_comment='大语言模型表',
        schema=None
    )
    op.drop_table_comment(
        'model_provider',
        existing_comment='模型供应商表',
        schema=None
    )
    op.drop_table('tools')
    # ### end Alembic commands ###
