"""供应商表新增api_type字段

Revision ID: f39bf6983d16
Revises: 22cb2ca576a1
Create Date: 2026-06-23 15:17:25.088057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39bf6983d16'
down_revision: Union[str, Sequence[str], None] = '22cb2ca576a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_provider', sa.Column('api_type', sa.String(length=20), nullable=False, comment='API类型: chat/responses'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_provider', 'api_type')
    # ### end Alembic commands ###
